sudo: required

services:
  - docker

env:
  matrix:
    - NODE_VERSION=latest
    - NODE_VERSION=6.3.1
    - NODE_VERSION=6.3.0
    - NODE_VERSION=6.2.2
    - NODE_VERSION=6.2.1
    - NODE_VERSION=6.2.0
    - NODE_VERSION=6.1.0
    - NODE_VERSION=6.0.0
    - NODE_VERSION=5.12.0
    - NODE_VERSION=5.11.1
    - NODE_VERSION=5.11.0
    - NODE_VERSION=5.10.1
    - NODE_VERSION=5.10.0
    - NODE_VERSION=5.9.1
    - NODE_VERSION=5.9.0
    - NODE_VERSION=5.8.0
    - NODE_VERSION=5.7.1
    - NODE_VERSION=5.7.0
    - NODE_VERSION=5.6.0
    - NODE_VERSION=5.5.0
    - NODE_VERSION=5.4.1
    - NODE_VERSION=5.4.0
    - NODE_VERSION=5.3.0
    - NODE_VERSION=5.2.0
    - NODE_VERSION=5.1.1
    - NODE_VERSION=5.1.0
    - NODE_VERSION=5.0.0
    - NODE_VERSION=4.4.7
    - NODE_VERSION=4.4.6
    - NODE_VERSION=4.4.5
    - NODE_VERSION=4.4.4
    - NODE_VERSION=4.4.3
    - NODE_VERSION=4.4.2
    - NODE_VERSION=4.4.1
    - NODE_VERSION=4.4.0
    - NODE_VERSION=4.3.2
    - NODE_VERSION=4.3.1
    - NODE_VERSION=4.3.0
    - NODE_VERSION=4.2.6
    - NODE_VERSION=4.2.5
    - NODE_VERSION=4.2.4
    - NODE_VERSION=4.2.3
    - NODE_VERSION=4.2.2
    - NODE_VERSION=4.2.1
    - NODE_VERSION=4.2.0
    - NODE_VERSION=4.1.2
    - NODE_VERSION=4.1.1
    - NODE_VERSION=4.1.0
    - NODE_VERSION=4.0.0
    - NODE_VERSION=0.12.15
    - NODE_VERSION=0.12.14
    - NODE_VERSION=0.12.13
    - NODE_VERSION=0.12.12
    - NODE_VERSION=0.12.11
    - NODE_VERSION=0.12.10
    - NODE_VERSION=0.12.9
    - NODE_VERSION=0.12.8
    - NODE_VERSION=0.12.7
    - NODE_VERSION=0.12.6
    - NODE_VERSION=0.12.5
    - NODE_VERSION=0.12.4
    - NODE_VERSION=0.12.3
    - NODE_VERSION=0.12.2
    - NODE_VERSION=0.12.1
    - NODE_VERSION=0.12.0
    - NODE_VERSION=0.11.16
    - NODE_VERSION=0.11.15
    - NODE_VERSION=0.11.14
    - NODE_VERSION=0.11.13
    - NODE_VERSION=0.11.12
    - NODE_VERSION=0.11.11
    - NODE_VERSION=0.11.10
    - NODE_VERSION=0.11.9
    - NODE_VERSION=0.11.8
    - NODE_VERSION=0.11.7
    - NODE_VERSION=0.11.6
    - NODE_VERSION=0.11.5
    - NODE_VERSION=0.11.4
    - NODE_VERSION=0.11.3
    - NODE_VERSION=0.11.2
    - NODE_VERSION=0.11.1
    - NODE_VERSION=0.11.0
    - NODE_VERSION=0.10.46
    - NODE_VERSION=0.10.45
    - NODE_VERSION=0.10.44
    - NODE_VERSION=0.10.43
    - NODE_VERSION=0.10.42
    - NODE_VERSION=0.10.41
    - NODE_VERSION=0.10.40
    - NODE_VERSION=0.10.39
    - NODE_VERSION=0.10.38
    - NODE_VERSION=0.10.37
    - NODE_VERSION=0.10.36
    - NODE_VERSION=0.10.35
    - NODE_VERSION=0.10.34
    - NODE_VERSION=0.10.33
    - NODE_VERSION=0.10.32
    - NODE_VERSION=0.10.31
    - NODE_VERSION=0.10.30
    - NODE_VERSION=0.10.29
    - NODE_VERSION=0.10.28
    - NODE_VERSION=0.10.27
    - NODE_VERSION=0.10.26
    - NODE_VERSION=0.10.25
    - NODE_VERSION=0.10.24
    - NODE_VERSION=0.10.23
    - NODE_VERSION=0.10.22
    - NODE_VERSION=0.10.21
    - NODE_VERSION=0.10.20
    - NODE_VERSION=0.10.19
    - NODE_VERSION=0.10.18
    - NODE_VERSION=0.10.17
    - NODE_VERSION=0.10.16
    - NODE_VERSION=0.10.15
    - NODE_VERSION=0.10.14
    - NODE_VERSION=0.10.13
    - NODE_VERSION=0.10.12
    - NODE_VERSION=0.10.11
    - NODE_VERSION=0.10.10
    - NODE_VERSION=0.10.9
    - NODE_VERSION=0.10.8
    - NODE_VERSION=0.10.7
    - NODE_VERSION=0.10.6
    - NODE_VERSION=0.10.5
    - NODE_VERSION=0.10.4
    - NODE_VERSION=0.10.3
    - NODE_VERSION=0.10.2
    - NODE_VERSION=0.10.1
    - NODE_VERSION=0.10.0
    - NODE_VERSION=0.9.12
    - NODE_VERSION=0.9.11
    - NODE_VERSION=0.9.10
    - NODE_VERSION=0.9.9
    - NODE_VERSION=0.9.8
    - NODE_VERSION=0.9.7
    - NODE_VERSION=0.9.6
    - NODE_VERSION=0.9.5
    - NODE_VERSION=0.9.4
    - NODE_VERSION=0.9.3
    - NODE_VERSION=0.9.2
    - NODE_VERSION=0.9.1
    - NODE_VERSION=0.9.0
    - NODE_VERSION=0.8.28
    - NODE_VERSION=0.8.27
    - NODE_VERSION=0.8.26
    - NODE_VERSION=0.8.25
    - NODE_VERSION=0.8.24
    - NODE_VERSION=0.8.23
    - NODE_VERSION=0.8.22
    - NODE_VERSION=0.8.21
    - NODE_VERSION=0.8.20
    - NODE_VERSION=0.8.19
    - NODE_VERSION=0.8.18
    - NODE_VERSION=0.8.17
    - NODE_VERSION=0.8.16
    - NODE_VERSION=0.8.15
    - NODE_VERSION=0.8.14
    - NODE_VERSION=0.8.13
    - NODE_VERSION=0.8.12
    - NODE_VERSION=0.8.11
    - NODE_VERSION=0.8.10
    - NODE_VERSION=0.8.9
    - NODE_VERSION=0.8.8
    - NODE_VERSION=0.8.7
    - NODE_VERSION=0.8.6
    - NODE_VERSION=0.8.5
    - NODE_VERSION=0.8.4
    - NODE_VERSION=0.8.3
    - NODE_VERSION=0.8.2
    - NODE_VERSION=0.8.1
    - NODE_VERSION=0.8.0
    - NODE_VERSION=0.7.12
    - NODE_VERSION=0.7.11
    - NODE_VERSION=0.7.10
    - NODE_VERSION=0.7.9
    - NODE_VERSION=0.7.8
    - NODE_VERSION=0.7.7
    - NODE_VERSION=0.7.6
    - NODE_VERSION=0.7.5
    - NODE_VERSION=0.7.4
    - NODE_VERSION=0.7.3
    - NODE_VERSION=0.7.2
    - NODE_VERSION=0.7.1
    - NODE_VERSION=0.7.0
    - NODE_VERSION=0.6.21
    - NODE_VERSION=0.6.20
    - NODE_VERSION=0.6.19
    - NODE_VERSION=0.6.18
    - NODE_VERSION=0.6.17
    - NODE_VERSION=0.6.16
    - NODE_VERSION=0.6.15
    - NODE_VERSION=0.6.14
    - NODE_VERSION=0.6.13
    - NODE_VERSION=0.6.12
    - NODE_VERSION=0.6.11
    - NODE_VERSION=0.6.10
    - NODE_VERSION=0.6.9
    - NODE_VERSION=0.6.8
    - NODE_VERSION=0.6.7
    - NODE_VERSION=0.6.6
    - NODE_VERSION=0.6.5
    - NODE_VERSION=0.6.4
    - NODE_VERSION=0.6.3
    - NODE_VERSION=0.6.2
    - NODE_VERSION=0.6.1
    - NODE_VERSION=0.6.0
    - NODE_VERSION=0.5.10
    - NODE_VERSION=0.5.9
    - NODE_VERSION=0.5.8
    - NODE_VERSION=0.5.7
    - NODE_VERSION=0.5.6
    - NODE_VERSION=0.5.5
    - NODE_VERSION=0.5.4
    - NODE_VERSION=0.5.3
    - NODE_VERSION=0.5.2
    - NODE_VERSION=0.5.1
    - NODE_VERSION=0.5.0
    - NODE_VERSION=0.4.12
    - NODE_VERSION=0.4.11
    - NODE_VERSION=0.4.10
    - NODE_VERSION=0.4.9
    - NODE_VERSION=0.4.8
    - NODE_VERSION=0.4.7
    - NODE_VERSION=0.4.6
    - NODE_VERSION=0.4.5
    - NODE_VERSION=0.4.4
    - NODE_VERSION=0.4.3
    - NODE_VERSION=0.4.2
    - NODE_VERSION=0.4.1
    - NODE_VERSION=0.4.0
    - NODE_VERSION=0.3.8
    - NODE_VERSION=0.3.7
    - NODE_VERSION=0.3.6
    - NODE_VERSION=0.3.5
    - NODE_VERSION=0.3.4
    - NODE_VERSION=0.3.3
    - NODE_VERSION=0.3.2
    - NODE_VERSION=0.3.1
    - NODE_VERSION=0.3.0
    - NODE_VERSION=0.2.6
    - NODE_VERSION=0.2.5
    - NODE_VERSION=0.2.4
    - NODE_VERSION=0.2.3
    - NODE_VERSION=0.2.2
    - NODE_VERSION=0.2.1
    - NODE_VERSION=0.2.0
    - NODE_VERSION=0.1.104
    - NODE_VERSION=0.1.103
    - NODE_VERSION=0.1.102
    - NODE_VERSION=0.1.101
    - NODE_VERSION=0.1.100
    - NODE_VERSION=0.1.99
    - NODE_VERSION=0.1.98
    - NODE_VERSION=0.1.97
    - NODE_VERSION=0.1.96
    - NODE_VERSION=0.1.95
    - NODE_VERSION=0.1.94
    - NODE_VERSION=0.1.93
    - NODE_VERSION=0.1.92
    - NODE_VERSION=0.1.91
    - NODE_VERSION=0.1.90
    - NODE_VERSION=0.1.33
    - NODE_VERSION=0.1.32
    - NODE_VERSION=0.1.31
    - NODE_VERSION=0.1.30
    - NODE_VERSION=0.1.29
    - NODE_VERSION=0.1.28
    - NODE_VERSION=0.1.27
    - NODE_VERSION=0.1.26
    - NODE_VERSION=0.1.25
    - NODE_VERSION=0.1.24
    - NODE_VERSION=0.1.23
    - NODE_VERSION=0.1.22
    - NODE_VERSION=0.1.21
    - NODE_VERSION=0.1.20
    - NODE_VERSION=0.1.19
    - NODE_VERSION=0.1.18
    - NODE_VERSION=0.1.17
    - NODE_VERSION=0.1.16
    - NODE_VERSION=0.1.15
    - NODE_VERSION=0.1.14

script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- make VERSION=${NODE_VERSION} push
- make VERSION=${NODE_VERSION}-onbuild push
- make VERSION=${NODE_VERSION}-development push
