before_install:
  - |

    declare -r SSH_FILE="$(realpath .travis/github_deploy_key)"

    openssl aes-256-cbc \
      -K $encrypted_c0f12bd67831_key \
      -iv $encrypted_c0f12bd67831_iv \
      -in ".travis/github_deploy_key.enc" \
      -out "$SSH_FILE" -d

    chmod 600 "$SSH_FILE"

    printf "%s\n" \
      "Host github.com" \
      "  IdentityFile $SSH_FILE" \
      "  LogLevel ERROR" >> ~/.ssh/config

script:
  - make deploy
